services:
  bdCB2:
    image: mysql:8.0
    platform: linux/arm64
    container_name: bdCB2
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CodigoBarras
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 12345
      MYSQLD_OPTS: "--innodb-force-recovery=3"
    volumes:
      - ./mysql_data:/var/lib/mysql
