services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./CodigoBarras:/var/www/html
    depends_on:
      bdCB:
        condition: service_healthy
    networks:
      - app-network

  bdCB:
    image: mysql:8.0.36
    platform: linux/arm64
    container_name: bdCB
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CodigoBarras
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: bdCB
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - "8080:80"
    depends_on:
      - bdCB
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
