services:
  mysql:
    image: mysql:8.0
    container_name: mysql_agil
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labunidos 
      MYSQL_USER: agil_user
      MYSQL_PASSWORD: 1234
      TZ: 'America/Bogota'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
