INSERT INTO categorias (cate_nombre, activo) VALUES ('Tecnología', true);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Gastronomía', true);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Deportes', true);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Moda', true);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Viajes', false);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Educación', true);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Salud', true);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Entretenimiento', false);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Arte y cultura', true);
INSERT INTO categorias (cate_nombre, activo) VALUES ('Economía y negocios', true);